language: python
sudo: false


install:
  - time ci/setup

script:
  - time ci/test


notifications:
  email: false

python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.4'
  - '3.3'


env:
  - env: UWSGI="2.0.1"
  - env: UWSGI="2.0.14"
  - env: UWSGI="2.0.15"


matrix:
  include:
